version: '3'
volumes:
  postgres:
    external: true
  logs:
    external: true
  redis:
    external: true
  rabbitmq:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:11.4
    env_file:
    - ./config.dev.env
    ports:
    - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
      - logs:/var/log/

  rabbitmq:
    image: rabbitmq:3.7.17
    container_name: rabbit
    hostname: rabbit
    env_file:
      - ./config.dev.env
    ports:
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    env_file:
      - ./config.dev.env
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
