version: '3.7'

x-base-network: &base_network
  networks:
    - python_backend

volumes:
  postgres:
    external: false
  logs:
    external: false

networks:
  python_backend:
    external: false

services:
  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    env_file:
      - .config.env.local
    volumes:
      - postgres:/var/lib/postgresql/data/
      - logs:/var/log/
    <<: *base_network
