version: '3.7'

x-base: &base
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  env_file:
    - .config.env

x-base-network: &base_network
  networks:
    - python_backend

volumes:
  postgres:
    external: true
  logs:
    external: true
  redis:
    external: true
  rabbit:
    external: true

networks:
  python_backend:
    external: true

services:
  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    env_file:
      - .config.env
    volumes:
      - postgres:/var/lib/postgresql/data/
      - logs:/var/log/
    <<: *base_network

  web:
    <<: *base
    <<: *base_network
    command: ./backend-entrypoint.sh
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - db
      - rabbit
      - redis
    ports:
      - 8000:8000

  rabbit:
    image: rabbitmq:3.7.17
#    container_name: rabbit
#    hostname: rabbit
    env_file:
      - ./.config.env
    ports:
      - 5672:5672
    volumes:
      - rabbit:/var/lib/rabbitmq/
    <<: *base_network

  redis:
    image: redis:alpine
    hostname: redis
    env_file:
      - ./.config.env
    depends_on:
      - rabbit
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
    <<: *base_network

  celery_worker:
    <<: *base
    <<: *base_network
    command: celery -A f2f_Q3_2019 worker -l info
    depends_on:
      - redis
      - rabbit

  celery_beat:
    <<: *base
    <<: *base_network
    command: celery -A f2f_Q3_2019 beat -l info
    depends_on:
      - redis
      - rabbit
